version: 2.1
orbs:
  cypress: cypress-io/cypress@1.0.1
workflows:
  build:
    jobs:
      - cypress/install:
          environment: masterFirebaseConfig: $masterFirebaseConfig
          build: 'npm run build'
      - cypress/run:
          requires:
            - cypress/install
          start: 'npm start'
