export var constants = {
    title: "Match Annotator",
    minPwLength: 7,
    lightBlueHex: "#ADD8E6",
    numDaysBeforeNewAnnotationNeeded: 30,
    numberOfCurrentAnnotationsNeeded: 10,
    numberOfSecondsToleratedToBeCalledSameAnnotation: 3,
    temp: "hi, Mark",
    monthlyCost: 2,
    halfYearCost: 6,
    yearlyCost: 10,
    requiredAnnotationsPerMonth: 1,
    rootNodes: [
    "Advantage",
    "Guard Passes or Guard Pass Attempts",
    "Take Downs or Take Down Attempts",
    "Submissions or Submission Attempts",
    "Sweeps or Sweep Attempts",
    "Positional Changes",
    "Positions With Names That Do Not Score Points In Most Rule Sets",
    "Discliplinary Action",
    ],
    privilegeLevels: {
      1: 100,
      2: 200,
      3: 500,
      4: 1000,
      5: 1500,
      6: 2000,
      7: 3000,
      8: 4000,
      9: 5000,
      10: 10000
    },
    annotationVoteQuota: 10
  };
