export var constants = {
    genders: ["Female", "Male", "Mixed", "Non-binary", "Trans Female", "Trans Male", "Other"],
    title: "Match Annotator",
    activityName: "Brazilian jiu jitsu",
    minPwLength: 7,
    lightBlueHex: "#ADD8E6",
    numDaysBeforeNewAnnotationNeeded: 30,
    numberOfCurrentAnnotationsNeeded: 6,
    numberOfSecondsToleratedToBeCalledSameAnnotation: 3,
    defaultVideoUrlCode: "OXcM9hE5wUk",
    temp: "hi, Mark",
    monthlyCost: 2,
    monthlyCostString: "$2",
    halfYearCost: 6,
    yearlyCost: 10,
    requiredAnnotationsPerMonth: 1,
    rootNodes: [
    "Advantage",
    "Match Outcome",
    "Guard Passes or Guard Pass Attempts",
    "Take Downs or Take Down Attempts",
    "Submissions or Submission Attempts",
    "Sweeps or Sweep Attempts",
    "Positional Changes",
    "Positions With Names That Do Not Score Points In Most Rule Sets",
    "Discliplinary Action",
    ],
    privilegeLevels: {
      1: 100,
      2: 200,
      3: 500,
      4: 1000,
      5: 1500,
      6: 2000,
      7: 3000,
      8: 4000,
      9: 5000,
      10: 10000
    },
    annotationVoteQuota: 10,
    numberOfFlagsAnAnnotationNeedsBeforeReptuationDeduction: 3,
    numberOfPointsToDeductForBadAnnotation: 50,
    numberOfPointsToAwardForAnnotation: 10,
    minimumAnnotationRatingThatAVideoFlaggedAsRemovedNeedsToPreventMajorityAnnotatorDeduction: 3.5,
    numberOfFlagsAnAnnotationNeedsBeforeItIsDisplayedToDrawAttention: 1
  };
